### ISSUE TITLE
Group the skills

### ISSUE THREAD

**Issue by colabcolibri** [bdecentgmbh/moodle-tool_skills#2]
I'm thinking about using the plugin to track skill from different groups. Like

Group A
- Skill 1
- Skill 2
- Skill 3

Group B
- Skill 4
- Skill 5

And so on.

Do you think it is feasible to create this sort of hierarchy, to group the skills?

**Comment by stefanscholz** [comment]
Hi @colabcolibri,

this plugin is currently tested and rolled out on one of our customer's sites, and they do something like this, at least sort of.

They want to track both the progress in specific skills, e.g. "Excel" or "Powerpoint", but also "Office" (= "Excel" + "Powerpoint"). On their site, what we do is we add both "Excel" and "Office" to the course where "Excel" skills are taught, and both "Word" and "Office" in the other course.

On the main dashboard, we display the "Excel" skills progress and the "Word" skills progress separately. On a different for the line managers, we only display "Office" skills progress, because it is not important for line managers to see which exact skill they are learning, only the overall progress. 

I assume that such a strategy could work for you as well.

Note that this is (respectively will be) the first (public) release of the plugin, we plan to improve the plugin over time and add more features to it. I think "grouping" skills makes a lot of sense, so I've added this to our backlog, which we review during the planning phase of each release. 

I'd love to hear more about your use case/scenario, so that we can consider this while we work on the specification.

If you would like to fund such a feature (and thus get it sooner), feel free to reach out privately (sts@bdecent.de) and we can discuss the details.

All the best
Stefan
